### PR TITLE
Calculate Jacobian Inverse

### PR DESCRIPTION
**Pull request by francesco-donofrio**
This PR introduces a method for computing the Jacobian inverse, along with a corresponding KDL implementation.

### CODE REVIEW

**Comment by progtologist** [comment]
Please add some unit tests to improve coverage

**Review by christophfroehlich — CHANGES_REQUESTED** [review]
As already mentioned, please consider adding some unit tests.
And I'd prefer to use the new method also in
`convert_cartesian_deltas_to_joint_deltas` instead of duplicating the calculation?

**Comment by delipl** [comment]
Do you need any help with that?
I would love to pass this feature.

**Comment by francescodonofrio** [comment]
Hi @delipl, thank you for your support. However, I’m currently waiting for the reviewers.

**Review by christophfroehlich — APPROVED** [review]
Thanks for the follow-up. Sorry that I haven't responded earlier.

**Comment by christophfroehlich** [comment]
@francesco-donofrio please merge the master into your branch (you have deactivated maintainer access?), the new clang workflow is missing here.

**Review by christophfroehlich — CHANGES_REQUESTED** [review]
@francesco-donofrio please merge the master into your branch (you have deactivated maintainer access?), the new clang workflow is missing here.

**Comment by francescodonofrio** [comment]
@Mergifyio refresh

**Comment by francescodonofrio** [comment]
@christophfroehlich I've merged the master into my branch.

**Review by christophfroehlich — APPROVED** [review]
clang job fails due to upstream regression. Tested locally!

**Comment by francescodonofrio** [comment]
@christophfroehlich @bmagyar Thank you for your work!

**Pull request merged**
